include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart" # Exclude generated files
    - "**/*.freezed.dart" # Exclude generated files

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20 
    halstead-volume: 1000 
    lines-of-code: 100 
    maximum-nesting-level: 5 
    number-of-parameters: 5 
    source-lines-of-code: 80 
    maintainability-index: 50 
  metrics-exclude:
    - test/** 
  rules:
    # Anda juga bisa menambahkan aturan lint di sini jika ingin.
    # Contoh:
    # - avoid-unnecessary-setstate
    # - prefer-trailing-comma
    # dll.