name: tugas2teori
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  go_router: ^15.0.0
  provider: ^6.1.4
  url_launcher: ^6.3.1
  webview_flutter: ^4.4.2
  intl: ^0.18.1
  geocoding: ^4.0.0
  http: ^1.4.0
  timezone: ^0.10.1
  sqflite: ^2.3.0
  path: ^1.8.3   
  crypto: ^3.0.3
  image_picker: ^1.0.7
  sensors_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  sqflite_common_ffi: ^2.3.0
  integration_test: 
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true

